version: '3.5'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: lanchonete_db
    ports:
      - "3306:3306"
    networks:
      - tech_challenge_app_network
    expose:
      - 3306

  mock:
    build:
      context: wiremock
    image: wiremock/wiremock
    ports:
      - "8081:8080"
    networks:
      - tech_challenge_app_network
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/logs:/home/wiremock/logs

  localstack:
    container_name: lanchonete_localstack
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"
    networks:
      - tech_challenge_app_network  # external services port range
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin
      AWS_REGION: us-east-1
networks:
  tech_challenge_app_network:
    name: "tech_challenge_app_network"
    driver: bridge