version: '3.5'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: lanchonete_db
    ports:
      - "3306:3306"
    networks:
      - tech_challenge_app_network
    expose:
      - 3306
  localstack:
    container_name: tech-challenge-localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin
      AWS_REGION: us-east-1
    volumes:
      - './docker/localstack/setup-queues.sh:/etc/localstack/init/ready.d/init-sqs.sh'
networks:
  tech_challenge_app_network:
    name: "tech_challenge_app_network"
    driver: bridge