version: '3.1'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: lanchonete_db
    ports:
      - "3306:3306"
    expose:
      - 3306
  mock:
    build:
      context: ./mock
    image: wiremock/wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./mock/__files:/home/wiremock/__files
      - ./mock/mappings:/home/wiremock/mappings
      - ./mock/logs:/home/wiremock/logs