apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete
  labels:
    app: lanchonete
spec:
  template:
    metadata:
      name: lanchonete
      labels:
        app: lanchonete
    spec:
      containers:
        - name: lanchonete
          image: vwnunes/tech-challenge-61:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: configmap
          env:
            - name: DB_HOST
              value: ${DB_HOST}
            - name: DB_USERNAME
              value: ${DB_USERNAME}
            - name: DB_PASSWORD
              value: ${DB_PASSWORD}
          volumeMounts:
            - mountPath: /lanchonete-volume
              name: lanchonete-volume
      volumes:
        - name: lanchonete-volume
          hostPath:
            path: /home/lanchonete-volume
            type: DirectoryOrCreate
  replicas: 2
  selector:
    matchLabels:
      app: lanchonete
