name: Check if PR already exists
description: Check if PR already exists

inputs:
  source_branch:
    description: 'Source branch'
    required: true
  target_branch:
    description: 'Target branch'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check if PR already exists
      id: pr_check
      run: |
        PR_EXISTING=$(gh pr list \
                    --repo ${{ github.repository }} \
                    -B ${{ inputs.target_branch }} \
                    -H ${{ inputs.source_branch }} \
                    --json number \
                    --jq '.[0].number')
        if (($PR_EXISTING > 0)); then
            echo Existing PR number: $PR_EXISTING
            echo "skip=true" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
