name: Build and Create PR to Main

on:
  pull_request:
    types: closed
    merged: true
    branches: develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: ./.github/actions/build

  create_pull_request:
    name: Create Pull Request to Main
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: ./.github/actions/create-pull-request
        with:
          source_branch: 'develop'
          target_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
